# Grafana datasource configuration for Prometheus

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    editable: true
    jsonData:
      client: standalone
    secureJsonData:
      password: ""
      
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: sneakersniper
    user: postgres
    editable: true
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: "postgres"
      
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Redis
    orgId: 1
  - name: PostgreSQL
    orgId: 1