name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Sneak-n-Snipe/services/api/requirements.txt"
          pip install -r "Sneak-n-Snipe/worker/requirements.txt"
          pip install ruff mypy pytest pytest-xdist safety bandit

      - name: Lint with ruff
        run: ruff check .

      - name: Type-check with mypy
        run: mypy .

      - name: Test with pytest
        run: pytest --numprocesses=auto

      - name: Security scan with safety
        run: safety check

      - name: Security scan with bandit
        run: bandit -r .
